###
GET http://localhost:4444/usuario

###
POST http://localhost:4444/usuario
Content-Type: application/json

{
    "email": "teste2@teste.com",
    "password": "123456",
    "nome": "teste" 
}

###
GET http://localhost:4444/papel

###
POST http://localhost:4444/papel
Content-Type: application/json

{
    
    "nome": "teste", 
    "papel": "MXRF11", 
    "tipoDeRenda": "fixa", 
    "tipoDeInvestimento": "", 
    "taxasIncidentes": ""
}